GET http://localhost:3001/api/v1/version HTTP/1.1
Host: localhost
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imd1ZXN0QGdtYWlsLmNvbSIsInByaXZpbGVnZXMiOlsiZ3Vlc3QiXSwiaWF0IjoxNzM2ODgyNzg0LCJleHAiOjE3MzY4ODMwODR9.oIN5Y91BfGnVdWsx2QNYUyFHvKb2cY-1XR3Qv7EnzAw
